### ISSUE TITLE
Lines removed in stylesheet and optionally link to external one

### ISSUE THREAD

**Issue by megadr01d** [rss2email/rss2email#7]
The CSS option in `rss2email.cfg` is broken since the first rss2email for python3 iteration. Since the JSON format removes comments, it removes both the `#entry` and `#body` lines (they're `div`s, not comments) from the CSS bit in the config file, each time we run rss2email.

```css
h1 {
    font: 18pt Georgia, "Times New Roman";
}
body {
    font: 12pt Arial;
}
a:link {
    font: 12pt Arial;
    font-weight: bold;
    color: #0000cc;
}
blockquote {
    font-family: monospace;
}
.header {
    background: #e0ecff;
    border-bottom: solid 4px #c3d9ff;
    padding: 5px;
    margin-top: 0px;
    color: red;
}
.header a {
    font-size: 20px;
    text-decoration: none;
}
.footer {
    background: #c3d9ff;
    border-top: solid 4px #c3d9ff;
    padding: 5px;
    margin-bottom: 0px;
}
#entry { ---> LINE REMOVED
    border: solid 4px #c3d9ff;
}
#body { ---> LINE REMOVED
    margin-left: 5px;
    margin-right: 5px;
}
```

My question is, wouldn't a better option be linking to an external stylesheet like so?

```cfg
...
use-css = True
css = rss2email.css ---> path to stylesheet file, just the filename if on the same folder as config
unicode-snob = False
...
```
